### ISSUE TITLE
File not getting downloaded

### ISSUE THREAD

**Issue by TheAsteroid894** [Imrglop/Latite-Releases#2]
When I was on the website of latite to download my browser(Chrome) didnt let me saying that it is a harmful and there is no file for it on github for downloading. Can you help me?

**Comment by TheAsteroid894** [comment]
And do I need a real copy of Minecraft Bedrock Edition?

**Comment by Plextora** [comment]
https://support.microsoft.com/en-us/windows/turn-off-defender-antivirus-protection-in-windows-security-99e6004f-c54c-8509-773c-a4d776b77960

also, this is the wrong place to report this
